"""Add user relationship to Reservation

Revision ID: 10fc6b7b6a35
Revises: e622975651ff
Create Date: 2023-04-17 19:38:02.412568

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '10fc6b7b6a35'
down_revision = 'e622975651ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_reservation_user_id_user', 'user', ['user_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_reservation_user_id_user', type_='foreignkey'
        )
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
